### ISSUE TITLE
Paper Timings not detected correctly

### ISSUE THREAD

**Issue by aikar** [aikar/minecraft-timings#1]
re: https://github.com/aikar/commands/issues/33

```12.05 15:31:15 [Server] WARN org.bukkit.plugin.AuthorNagException: Deprecated use of CustomTimingsHandler. Please Switch to Timings.of ASAP 
12.05 15:31:15 [Server] WARN at org.spigotmc.CustomTimingsHandler.<init>(CustomTimingsHandler.java:58) 
12.05 15:31:15 [Server] WARN at hu.tryharddevs.advancedkits.utils.timings.lib.SpigotTiming.<init>(SpigotTiming.java:11) 
12.05 15:31:15 [Server] WARN at hu.tryharddevs.advancedkits.utils.timings.lib.TimingType$1.newTiming(TimingType.java:11) 
12.05 15:31:15 [Server] WARN at hu.tryharddevs.advancedkits.utils.timings.lib.TimingManager.of(TimingManager.java:62) 
12.05 15:31:15 [Server] WARN at hu.tryharddevs.advancedkits.utils.afc.RegisteredCommand.getTiming(RegisteredCommand.java:214) 
12.05 15:31:15 [Server] WARN at hu.tryharddevs.advancedkits.utils.afc.BaseCommand.executeCommand(BaseCommand.java:393) 
12.05 15:31:15 [Server] WARN at hu.tryharddevs.advancedkits.utils.afc.BaseCommand.executeSubcommand(BaseCommand.java:471) 
12.05 15:31:15 [Server] WARN at hu.tryharddevs.advancedkits.utils.afc.BaseCommand.execute(BaseCommand.java:330) 
12.05 15:31:15 [Server] WARN at hu.tryharddevs.advancedkits.utils.afc.RootCommand.execute(RootCommand.java:71) 
12.05 15:31:15 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) 
```

**Comment by aikar** [comment]
@TryHardDood please let me know server version, i'm assuming it's 1.8

**Comment by benjaminforras** [comment]
My plugin does not work on 1.8, it disables itself. (I'll update you when I hear anything from that user.)

**Comment by aikar** [comment]
Per https://github.com/aikar/commands/issues/33#issuecomment-301660289 - Bug in your gradle file
